### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-oao8k#3]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by RitvikSaranS** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/88278326/182635723-6d5dee72-6d73-486b-960e-b12a45acffea.png)

**Comment by RitvikSaranS** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/88278326/182636118-86701eb5-2f93-4761-91f3-82099a566a95.png)
